function epochs = ImportEpochs(group,...
        params,...
        data,...
        inputSources,...
        protocol,...
        analysisProtocol)
    
    import ovation.*;
    epochDescriptors = splitEpochs(data.Laps);
    
    for i = 1:length(epochDescriptors)
        disp(['  Epoch ' num2str(i) '...']);
        epochs(i) = importEpoch(group,...
            protocol,...
            params,...
            data,...
            epochDescriptors(i),...
            inputSources,...
            analysisProtocol); %#ok<AGROW>
    end
end