%% Context
ctx = NewDataContext();

%% Project
% project = ctx.insertProject('Pastalkova Import', 'Testing Pastalkova Lab importer', datetime());

project = ctx.getObjectWithURI('ovation://a63a1654-cd85-42b1-b4ad-bb8b78824d00/');

%% Protocols

% srcProtocol = ctx.insertProtocol('Source Protocol',...
%     'Source derivation protocol mouse => brain area');

srcProtocol = ctx.getObjectWithURI('ovation://71e07958-0199-40e8-930c-3caf595dcfb8/');

% expProtocol = ctx.insertProtocol('Experiment Protocol',...
%     'Exp protocol');

expProtocol = ctx.getObjectWithURI('ovation://93b8833e-3526-4c3e-8b83-980e5588c622/');


% epochProtocol = ctx.insertProtocol('Epoch Protocol',...
%     'Epoch protocol');

epochProtocol = ctx.getObjectWithURI('ovation://7539d9fc-754b-45fc-85d3-27174da619e4/');

% analysisProtocol = ctx.insertProtocol('Analysis Protocol',...
%     'Analysis Protocol');

analysisProtocol = ctx.getObjectWithURI('ovation://f5798530-e1c7-4f9f-ae7b-420e0be47b36/');


%% Parameters
[~,grp, sourceMap] = importParameters(ctx,...
    project,...
    params,...
    data.xml,...
    expProtocol,...
    srcProtocol,...
    [],...
    []);

%% Epoch
 d = splitEpochs(data.Laps);
 
ind = 4;
epoch = importEpoch(grp,...
    epochProtocol,...
    params, ...
    data,...
    d(ind),...
    sourceMap,...
    analysisProtocol);